# Generated by Django 2.1.5 on 2019-01-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EbayUsername', models.CharField(max_length=30)),
                ('EbayPassword', models.CharField(max_length=30)),
            ],
        ),
    ]
