# Generated by Django 2.1.5 on 2019-01-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDistroUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdDistroUsername', models.CharField(max_length=30)),
                ('AdDistroPassword', models.CharField(max_length=30)),
            ],
        ),
    ]
