# Generated by Django 2.1.5 on 2019-01-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_addistrouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdDistroUser',
        ),
        migrations.DeleteModel(
            name='EbayUser',
        ),
    ]
