# Generated by Django 2.1.5 on 2019-01-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adIndex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='packageHeight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ad',
            name='packageLength',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ad',
            name='packageUnitMeasurement',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='ad',
            name='packageWeight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ad',
            name='packageWidth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ad',
            name='postTo',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
