# Generated by Django 2.1.5 on 2019-01-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adIndex', '0002_auto_20190119_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDistroUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdDistroUsername', models.CharField(max_length=30)),
                ('AdDistroPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EbayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EbayUsername', models.CharField(max_length=30)),
                ('EbayPassword', models.CharField(max_length=30)),
            ],
        ),
    ]
